# Generated by Django 3.2.13 on 2023-01-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
